
/*var tipuesearch = {"pages": [
     {"title": "Tipue", "text": "Tipue is a small web development studio based in North London.", "url": "http://www.tipue.com"}, 
     {"title": "Tipue Search, a jQuery Site Search Plugin", "text": "Tipue Search is a site search jQuery plugin. It's free, open source, responsive and fast. Tipue Search only needs a browser that supports jQuery. It doesn't need MySQL or similar. It doesn't even need a web server.", "img": "http://www.tipue.com/img/surface.jpg", "tags": "JavaScript", "url": "http://www.tipue.com/search"},
     {"title": "Tipue Search Help", "text": "Tipue Search help. Tipue Search is a site search jQuery plugin. It's free, open source, responsive and fast. What is Tipue Search? Getting Started. Using Tipue Search. Options.", "img": "http://www.tipue.com/img/elvis.jpg", "url": "http://www.tipue.com/search/help"},
     {"title": "Tipue Search demo", "text": "Tipue Search demo. Try searching for Tipue.", "url": "http://www.tipue.com/search/demo"},
     {"title": "About Tipue", "text": "Tipue is a small web development studio based in North London, founded in 2001. We design innovative and original jQuery plugins and add-in code. We talk to MySQL and similar with heavy-duty Perl. Our work breathes.", "url": "http://www.tipue.com/is"},     
     {"title": "Tipr, a Small and Simple jQuery Tooltip Plugin", "text": "Small, simple, flat, cool. Tipr is a jQuery tooltip plugin. It works on almost any element, and it's free and open source. Tipr displays nice tooltips, and it's around 3KB, CSS included. The tooltips can appear on almost any HTML element. Tipr reacts to the size of the viewport.", "img": "http://www.tipue.com/img/glow.jpg", "tags": "JavaScript", "url": "http://www.tipue.com/tipr"},
     {"title": "Tipue Support", "text": "We offer a range of flexible support plans for our jQuery plugins, including free. We hope to continue offering excellent free support. Get it by talking to us on Twitter.", "url": "http://www.tipue.com/support"},     
     {"title": "Getting Started with Tipue Search", "text": "Download Tipue Search and copy the tipuesearch folder to your site. You should look at the demo included with Tipue Search. You should first create a search page. The site content is stored in the tipuesearch_content.js file. It contains the search data as a JavaScript object.", "note": "<a href='http://www.tipue.com/search/help/'>From Help</a>", "url": "http://www.tipue.com/search/help/?d=1"},
     {"title": "Content for Tipue Search", "text": "The search data for Tipue Search is contained in the tipuesearch JavaScript object. Usually this is stored in the tipuesearch_content.js file, but it doesn't have to be. You can create a JavaScript object for your website with Beaty.", "note": "<a href='http://www.tipue.com/search/help/'>From Help</a>", "url": "http://www.tipue.com/search/help/?d=2"},
     {"title": "Beaty", "text": "Beaty is a web scraper that grabs content from your website and returns the data as a JavaScript object, JSON or CSV. Beaty is for small to medium websites, and there's a limit of 70 pages. English is the only language supported.", "tags": "Tipue", "url": "http://www.tipue.com/beaty"},
     {"title": "The Complete Guide to Centering a Div", "text": "Every developer inevitably finds that centering a div isn't as obvious as you'd expect. Centering what's inside a div horizontally is easy but then things tend to get a bit sticky. When you get to centering a div vertically, you can end up in a world of CSS hurt.", "tags": "Tipue Features", "url": "http://www.tipue.com/blog/center-a-div"},
     {"title": "Using Vw and Vh", "text": "Viewport width (vw) and viewport height (vh) are viewport-percentage values introduced in CSS3. Given how powerful they are, and with almost complete browser support, they should be everywhere.", "tags": "Tipue Features", "url": "http://www.tipue.com/blog/css3-vw-vh"},     
     {"title": "Using CSS Feature Queries", "text": "CSS feature queries are now supported everywhere. They allow you to use cutting edge CSS with subtle and precise feature detection.", "tags": "Tipue Features", "url": "http://www.tipue.com/blog/feature-queries"},     
     {"title": "A Very Simple CSS Background Zoom", "text": "A really easy method of creating a CSS background image zoom. Not only is this simple, it comes with wide browser support.", "tags": "Tipue Features", "url": "http://www.tipue.com/blog/css-background-zoom"},
     {"title": "Using Z-index", "text": "The CSS z-index property often trips up both new and experienced developers. The aim of this article is to boil down a somewhat-complex specification to three major points, which should ease most z-index pain.", "tags": "Tipue Features", "url": "http://www.tipue.com/blog/z-index"}
]};*/
var tipuesearch = {"pages": [
	{"title":"Murieta Owners Association : Home", "text": "Murieta Owners Association : Home +1 (510) 683-8794 (510) 683-8940 murietahoa@gmail.com � Login Remember me SIGN IN Forgot password ? No account ? Sign Up. � Sign Up Already got account? Sign In. Remember me SIGN UP Toggle navigation Murieta Home Events News Photos Documents & Info Governing Documents Community Info Forms, Fees & Insurance City Agencies & Orgs Davis Stirling Act Home Services Contact Us Murieta Owner's Association 39821 Cedar Blvd., Newark, CA 94560 Office is located in the North Clubhouse About us Murieta Background The Murieta complex was built in 1983 by the Duffel Company. First opened in 1984, Murieta is a 2 1\/2 acre condominium complex located in the south part of Newark, CA. There are 324 units, varying from one to three bedrooms in size, spread out among 8 buildings. The place was architecturally built in Spanish motif. Large-arched entrance facades with hanging lamps greet all residents who venture inside. Pools, spas, jacuzzis and clubhouses are located on both the North and South sides of the clubhouses. Add the palm trees to the mix, and one could easily mistake the complex for a tropical resort! The business operations of Murieta are run by a Board of Directors. Each year, a new board is voted in by the homeowners. They determine a set of policies for establishing new initiatives, standards, and circumstances for continuing with existing operations. The board runs their meetings in accordance to Roberts Rules of Order. They hire a property manager to oversee the administration and maintenance of the complex. Each homeowner is given a set of governing rules called the CC&Rs. The CC&Rs (Covenants, Conditions and Restrictions) contains rights of ownership, easements, restrictions of usage, conditions for making assessments, and making improvements to the units and common areas. In addition, there are a set of by-laws which were enacted after the complex was opened. Maps and Addresses Building 2 39997 Cedar Blvd. Building 3 39953 Cedar Blvd. Building 6 39887 Cedar Blvd. Building 7 39843 Cedar Blvd. Building 1 39975 Cedar Blvd. Building 4 39931 Cedar Blvd. Building 5 39865 Cedar Blvd. Building 8 39821 Cedar Blvd. Murieta Owner's Association Office Hours Monday, Wednesday, Thursday & Friday 9:00 AM - 4:30 PM Tuesday 9:00 AM - 6:00 PM Saturday & Sunday Closed", "img": "", "url": "http://dev.murietahoa.org/index.php"},
	{"title":"Murieta Owner Association : Events", "text": "Murieta Owner Association : Events +1 (510) 683-8794 (510) 683-8940 murietahoa@gmail.com × Login Remember me SIGN IN Forgot password ? No account ? Sign Up. × Sign Up Already got account? Sign In. Remember me SIGN UP Toggle navigation Murieta Home Events News Photos Documents & Info Governing Documents Community Info Forms, Fees & Insurance City Agencies & Orgs Davis Stirling Act Home Services Contact Us Murieta Events Home Events Upcomming Events October 2018 October 1 to 8 The office will close at noon. Contact Office for details October 2 Applied Pest Management scheduled visit, 9:00 AM - 11:00 AM October 7 Yoga Class October 8 Women’s Koffee Klatch, N. Clubhouse, 9:00 a.m. October 9 Homeowner's Meeting, N. Clubhouse, 7:00 p.m. October 16 Applied Pest Management scheduled visit, 9:00 AM - 11:00 AM Finance Committee\/Budget Meeting, N. Clubhouse, 6:00 p.m. September 2018 September 2 Yoga Class @ 10:00 AM September 3 Labor Day Office closed September 4 Applied Pest Management scheduled visit, 9:00 AM - 11:00 AM September 10 Women’s Koffee Klatch, N. Clubhouse, 9:00 a.m. September 11 Finance Committee\/Budget Meeting, N. Clubhouse, 6:00 p.m. Homeowner's Meeting, N. Clubhouse, 7:00 p.m. September 18 Applied Pest Management scheduled visit, 9:00 AM - 11:00 AM August 2018 August 7 Mandatory Fire Alarm Testing – 39975 Cedar (Building 1) Applied Pest Management scheduled visit, 9:00 a.m. August 13 Women’s Koffee Klatch, N. Clubhouse, 9:00 a.m. August 14 Finance Committee\/Budget Meeting, N. Clubhouse, 6:00 p.m. Homeowner's Meeting, N. Clubhouse, 7:00 p.m. August 21 Mandatory Fire Alarm Testing – 39931 Cedar (Building 4) Applied Pest Management scheduled visit, 9:00 a.m. August 28 Mandatory Fire Alarm Testing – 39953 Cedar (Building 3) Murieta Owner's Association Office Hours Monday, Wednesday, Thursday & Friday 9:00 AM - 4:30 PM Tuesday 9:00 AM - 6:00 PM Saturday & Sunday Closed", "img": "", "url": "http://dev.murietahoa.org/events.php"}
]};